import React, { useState } from 'react';
import { ClipboardIcon, CheckIcon } from '@heroicons/react/solid';
import { useClipboard } from 'use-clipboard-copy';

import stepsToCreate from '../../assets/nextjs/layout1.jpeg';
import projectStructure from '../../assets/nextjs/layout2.jpeg';
import layoutJs from '../../assets/nextjs/layout3.jpeg';

const CodeBlock = ({ code }) => {
  const clipboard = useClipboard();
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    clipboard.copy(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative">
      <pre className="bg-gray-100 dark:bg-gray-800 p-4 rounded-md text-sm overflow-x-auto">
        <code>{code}</code>
      </pre>
      <button
        onClick={handleCopy}
        className="absolute top-2 right-2 flex items-center gap-1 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-100 px-2 py-1 rounded text-xs"
      >
        {copied ? (
          <>
            <CheckIcon className="h-4 w-4" /> Copied
          </>
        ) : (
          <>
            <ClipboardIcon className="h-4 w-4" /> Copy
          </>
        )}
      </button>
    </div>
  );
};

const NextJSLayoutComponent = () => {
  return (
    <div className="w-full max-w-screen-lg mx-auto px-4 sm:px-6 md:px-8 py-6 space-y-8 text-gray-800 dark:text-gray-100">
      <section className="space-y-4">
        <p className="text-base">
          Layout components in <strong>Next.js</strong> help you create consistent page structures across your application. These components maintain shared UI such as headers, footers, or sidebars and improve navigation performance.
        </p>
      </section>

      {/* Prerequisites */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Prerequisites</h2>
        <ul className="list-disc list-inside space-y-1">
          <li>JavaScript / TypeScript</li>
          <li>React JS Basics</li>
          <li>Next.js (App Router)</li>
        </ul>
      </section>

      {/* Layout Basics */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">How Layout Works in App Router</h2>
        <p className="text-base">
          In Next.js using the App Router, each folder inside the <code className="bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded">app/</code> directory represents a route.
          If a folder contains <code>page.js</code>, it's publicly accessible. Its layout is defined using <code>layout.js</code> in the same folder.
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li><strong>layout.js</strong> wraps <code>page.js</code> and remains persistent across navigations.</li>
          <li><strong>Root layout</strong> includes <code>html</code> and <code>body</code> tags and wraps all child layouts.</li>
          <li><strong>Layouts</strong> are server components and can fetch data.</li>
        </ul>
      </section>

      {/* Steps to Create */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Steps to Create the Project</h2>
        <CodeBlock code={`npx create-next-app@latest Demo-App`} />
        <p>Follow the prompts in your terminal. Here's a visual guide:</p>
        <img src={stepsToCreate} alt="Steps to Create the Project" className="rounded shadow-lg max-w-full" />
      </section>

      {/* Project Structure */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Project Structure</h2>
        <p>This is what your folder structure will look like:</p>
        <img src={projectStructure} alt="Project Structure" className="rounded shadow-lg max-w-full" />
        <CodeBlock
          code={`"dependencies": {
  "react": "^18",
  "react-dom": "^18",
  "next": "14.1.0"
}`}
        />
      </section>

      {/* Example Layout.js */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Root Layout Example</h2>
        <CodeBlock
          code={`// layout.js

import { Advent_Pro } from "next/font/google";
import "./globals.css";

const inter = Advent_Pro({ subsets: ["latin"], weight: '700' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`}
        />
        <img src={layoutJs} alt="layout.js Output" className="rounded shadow-lg max-w-full" />
      </section>

      <p className="text-center text-base mt-10 font-medium">
        Next Chapter: Navigate Between Pages in NextJS
      </p>
    </div>
  );
};

export default NextJSLayoutComponent;
